version: '3' 
networks:
  backend:
    name: backend
services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        php_version: ${PHP_VERSION}
    volumes:
        - ./:/var/www/html 
        - /var/www/html/vendor/  
    networks:
      - backend  
    depends_on:
      - app-redis

  app-nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./:/var/www/html 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - backend

  app-redis: 
    image: redis
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - ../data/redis:/data
    networks:
      - backend 