version: '3'
services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        php_version: ${PHP_VERSION}
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/vendor/
    networks:
      - default
    depends_on:
      - app-redis

  app-nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./:/usr/src/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app-redis: 
    image: redis
    expose:
      - 6300