version: '3' 
networks:
  backend:
    name: backend
services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        php_version: ${PHP_VERSION}
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/vendor/
    networks:
      - backend
    links:
      - app-redis
    depends_on:
      - app-redis

  app-nginx:
    image: nginx:latest
    restart: always
    ports: 
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./:/usr/src/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - backend

  app-redis: 
    image: redis
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - ../data/redis:/data
    networks:
      - backend 